safe:        true
auto:        false
server:      false
server_port: 4000
baseurl:     /

exclude: README.md, CONTRIBUTING.md

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    false
markdown:    kramdown
permalink:   date
